$schema: ../../schema/aip-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: warning
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5
