$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    mcp_agent:
      command: "uv"
      args: ["run", "server.py"]
    chroma:
      transport: "aip-sse"
      url: "http://0.0.0.0:8080"
    twitter:
      transport: "aip-sse"
      url: "http://0.0.0.0:8081"

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
