$schema: ../../schema/aip-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    agent_hub:
      transport: "aip-sse"
      url: "http://127.0.0.1:8080"
    mcp_agent:
      command: "uv"
      args: ["run", "mcp_server.py"]
    membase:
      #transport: "sse"
      #url: "http://127.0.0.1:8000/sse"
      command: uv
      args: ["run", "../../../membase-mcp/src/membase_mcp/server.py"]
      env:
        MEMBASE_ACCOUNT: membase-mcp-test
        MEMBASE_CONVERSATION_ID: conversation_test
        MEMBASE_ID: mcp

openai:
  # Secrets (API keys, etc.) are stored in an aip_agent.secrets.yaml file which can be gitignored
  # base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  # model_name: qwen-max
  # base_url: https://api.deepseek.com/v1
  # model_name: deepseek-chat
